### ISSUE TITLE
About memory usage

### ISSUE THREAD

**Issue by EdwardLi250** [Wendison/FCL-taco2#2]
How to reduce memory usage in the code? 
I tried to modify 'batch-size', but whatever I set, memory usage was always very high, and would return a 'CUDA out of memory' error. 

I use an RTX 2080Ti, so I suppose my gpu memory should be enough?

**Comment by Wendison** [comment]
Hi, in my case, I use RTX 2080 (~12GB) and set batch-size to 16, it takes around 8GB for running experiments by using apex. Without apex, it will exceed 12GB. Maybe you can try to install apex (https://github.com/NVIDIA/apex) to reduce the memory usage.

**Comment by EdwardLi250** [comment]
Thanks! I installed apex and enabled amp, it works
